import { Hexes } from "./Battle.types";

export const LEFT = -12;
export const TOP = 46;
export const HEX_WIDTH = 108;
export const HEX_HEIGHT = 94;
export const ACTION_POINTS = 4;
export const WIDTH = 11;
export const HEIGHT = 7;

export const defaultHexes: Hexes = {
    "0:0": {
        x: 0,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "0:1": {
        x: 0,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "0:2": {
        x: 0,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "0:3": {
        x: 0,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "0:4": {
        x: 0,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "0:5": {
        x: 0,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "0:6": {
        x: 0,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "1:0": {
        x: 1,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "1:1": {
        x: 1,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "1:2": {
        x: 1,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "1:3": {
        x: 1,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "1:4": {
        x: 1,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "1:5": {
        x: 1,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "1:6": {
        x: 1,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "2:0": {
        x: 2,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "2:1": {
        x: 2,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "2:2": {
        x: 2,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "2:3": {
        x: 2,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "2:4": {
        x: 2,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "2:5": {
        x: 2,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "2:6": {
        x: 2,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "3:0": {
        x: 3,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "3:1": {
        x: 3,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "3:2": {
        x: 3,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "3:3": {
        x: 3,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "3:4": {
        x: 3,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "3:5": {
        x: 3,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "3:6": {
        x: 3,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "4:0": {
        x: 4,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "4:1": {
        x: 4,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "4:2": {
        x: 4,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "4:3": {
        x: 4,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "4:4": {
        x: 4,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "4:5": {
        x: 4,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "4:6": {
        x: 4,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "5:0": {
        x: 5,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "5:1": {
        x: 5,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "5:2": {
        x: 5,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "5:3": {
        x: 5,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "5:4": {
        x: 5,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "5:5": {
        x: 5,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "5:6": {
        x: 5,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "6:0": {
        x: 6,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "6:1": {
        x: 6,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "6:2": {
        x: 6,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "6:3": {
        x: 6,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "6:4": {
        x: 6,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "6:5": {
        x: 6,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "6:6": {
        x: 6,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "7:0": {
        x: 7,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "7:1": {
        x: 7,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "7:2": {
        x: 7,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "7:3": {
        x: 7,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "7:4": {
        x: 7,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "7:5": {
        x: 7,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "7:6": {
        x: 7,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "8:0": {
        x: 8,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "8:1": {
        x: 8,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "8:2": {
        x: 8,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "8:3": {
        x: 8,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "8:4": {
        x: 8,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "8:5": {
        x: 8,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "8:6": {
        x: 8,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "9:0": {
        x: 9,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "9:1": {
        x: 9,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "9:2": {
        x: 9,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "9:3": {
        x: 9,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "9:4": {
        x: 9,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "9:5": {
        x: 9,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "9:6": {
        x: 9,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "10:0": {
        x: 10,
        y: 0,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
        isEmpty: true,
    },
    "10:1": {
        x: 10,
        y: 1,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "10:2": {
        x: 10,
        y: 2,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
        isEmpty: true,
    },
    "10:3": {
        x: 10,
        y: 3,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "10:4": {
        x: 10,
        y: 4,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
        isEmpty: true,
    },
    "10:5": {
        x: 10,
        y: 5,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
    },
    "10:6": {
        x: 10,
        y: 6,
        isPassable: true,
        isHighlighted: false,
        isWithUnit: false,
        isEmpty: true,
    },
};
